# Generated by Django 2.1.5 on 2019-01-10 10:27

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorite', '0008_remove_favorite_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=builtins.id, max_length=64, null=True)),
                ('password', models.CharField(blank=True, default=builtins.id, max_length=64, null=True)),
                ('favorite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='favorite.Favorite')),
            ],
        ),
    ]
