# Generated by Django 2.1.5 on 2019-01-10 11:03

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190110_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='login',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='password',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
