# Generated by Django 2.1.5 on 2019-01-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190110_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='login',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
