# Generated by Django 2.1.5 on 2019-01-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190110_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='login',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
