# Generated by Django 3.0.5 on 2020-04-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190110_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_in_purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField(default=None, null=True)),
                ('id_purchase', models.IntegerField(default=None, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('check', models.BooleanField(default=False)),
            ],
        ),
    ]
