# Generated by Django 3.0.5 on 2020-04-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_product_in_purchase_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cash',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
