# Generated by Django 2.1.5 on 2019-01-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfavorite',
            options={'verbose_name': 'Товар в фаворитах', 'verbose_name_plural': 'Товары в фаворитах'},
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='customer_name',
            new_name='girl_name',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='customer_phone',
            new_name='girl_phone',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='customer_address',
            new_name='store_address',
        ),
        migrations.RenameField(
            model_name='productinfavorite',
            old_name='favorite',
            new_name='favorites',
        ),
    ]
