# Generated by Django 2.1.5 on 2019-01-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_auto_20190109_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfavorite',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
    ]
