# Generated by Django 2.1.5 on 2019-01-09 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorite', '0004_auto_20190109_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinbasket',
            options={'verbose_name': 'Фавориты в списке', 'verbose_name_plural': 'Фавориты в списке'},
        ),
        migrations.RenameField(
            model_name='productinbasket',
            old_name='favorits',
            new_name='favorites',
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
