# Generated by Django 2.1.5 on 2019-01-10 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0005_auto_20190109_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfavorite',
            name='favorites',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='favorite.Favorite'),
        ),
    ]
