# Generated by Django 2.1.5 on 2019-01-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0007_auto_20190110_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
    ]
