# Generated by Django 2.1.5 on 2019-01-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0008_remove_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='favorite.Status'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='favorites',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='favorite.Favorite'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='product',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Product'),
        ),
        migrations.AlterField(
            model_name='productinfavorite',
            name='favorites',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='favorite.Favorite'),
        ),
        migrations.AlterField(
            model_name='productinfavorite',
            name='product',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Product'),
        ),
    ]
