# Generated by Django 2.1.5 on 2019-01-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0009_auto_20190110_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='nmb',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
